config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'homes#top'

  get 'homes/about' => "homes#about", as: "about"

  resources :post_images, only: [:new, :index, :show, :create, :destroy] do
  resource :favorite, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :user_id, uniqueness: {scope: :post_image_id}

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  validates :image, presence: true
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 201 }


   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end

  def favorited_by?(user)
   favorites.exists?(user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable


  has_one_attached :profile_image
  has_many :books
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :introduction, length: { maximum: 50 }
  validates :name, presence: true, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :name, uniqueness: true


 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top]
    before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    post_images_path
  end


  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

    def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path, notice: '投稿に成功しました'
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

    def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_path
  end


    private

  def post_image_params
    params.require(:post_image).permit(:title, :image, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to user_path(@user)
  else
    render 'edit'
  end
end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<html>

 <head>
    <title>Booker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <script src="https://kit.fontawesome.com/353e4c8b8d.js" crossorigin="anonymous"></script></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<body>
Welcome to Bookers!

</body>
</html>

app/views/homes/top.html.erb
<head>

<title>Booker2</title>

</head>


<body>
<% if notice %>
  <%= notice %>
<% end %>
<% if alert %>
  <%= alert %>
<% end %>

<h1>welcome to Bookers !!</h1>

<p>In <i class="fa-solid fa-book"></i>Bookers,</p>

<p>you can share and exchange  your opinions , inpressions , and emotions</p>

<p>about various books!</p>

<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>

<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <script src="https://kit.fontawesome.com/353e4c8b8d.js" crossorigin="anonymous"></script></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to "log out", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'books', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'user', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>


            <% else %>

            <li class="nav-item">
              <%= link_to "sign_up", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "log in", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
             <li class="nav-item">
              <%= link_to 'homes', root_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'about', about_path, class: 'nav-link text-dark' %>
            </li>

            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>

                <title="About" class="text-black">CopyRight Infratop.inc</title>

</html>

app/views/post_images/_list.html.erb
<% @post_images.each do |post_image| %>
  <div>
     <%= link_to post_image_path(post_image.id) do %>
    <%= image_tag post_image.get_image %>
  <% end %>

    <p>投稿ユーザー画像：<%= image_tag post_image.user.get_profile_image(100,100) %></p>

    <p>ユーザーネーム：<%= post_image.user.name %></p>

    <p>ショップ名：<%= post_image.shop_name %></p>

    <p>説明：<%= post_image.caption %></p>

     <% if post_image.user == current_user %>
    <%= link_to "削除", post_image_path(post_image), method: :delete %>
  <% end %>
    <p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>

  </div>
<% end %>
<%= paginate post_images %>

app/views/post_images/index.html.erb
<% if notice %>
  <%= notice %>
<% end %>
<% if alert %>
  <%= alert %>
<% end %>


<%= render 'list', post_images: @post_images %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>

<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <ul>
    <% @post_image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post_image do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>ショップ名</h4>
  <%= f.text_field :title %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
   <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
    <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>

<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
     <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <% if @user.id == current_user.id %>
  <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>

<!-- ユーザーの投稿一覧 -->
<%= render 'post_images/list', post_images: @post_images %>